# Generated by Django 4.2.13 on 2024-07-04 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly', models.CharField(choices=[('Local', 'Local'), ('Imported', 'Imported')], max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('engine_capacity', models.CharField(max_length=50, null=True)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=50, null=True)),
                ('millage', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
                ('registered_in', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=100)),
                ('transmission_type', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=50, null=True)),
                ('ad_created', models.DateTimeField(auto_now_add=True)),
                ('ad_last_updated', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(null=True)),
                ('seller_comments', models.TextField(blank=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.manufacturer')),
                ('features', models.ManyToManyField(to='cars.features')),
                ('images', models.ManyToManyField(blank=True, to='cars.images')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
            ],
        ),
    ]
