# Generated by Django 4.2.13 on 2024-07-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='CarManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body_type', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20, null=True)),
                ('year', models.IntegerField(null=True)),
                ('millage', models.CharField(max_length=20, null=True)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=50, null=True)),
                ('transmission_type', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=50, null=True)),
                ('registered_in', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('assembly', models.CharField(choices=[('Local', 'Local'), ('Imported', 'Imported')], max_length=50, null=True)),
                ('engine_capacity', models.CharField(max_length=50, null=True)),
                ('chasis_num', models.CharField(blank=True, max_length=50, null=True)),
                ('auction_num', models.CharField(blank=True, max_length=50, null=True)),
                ('ad_created', models.DateTimeField(auto_now_add=True)),
                ('ad_last_updated', models.DateTimeField(auto_now=True)),
                ('seller_comments', models.TextField(blank=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmanufacturer')),
                ('features', models.ManyToManyField(to='cars.carfeatures')),
                ('images', models.ManyToManyField(blank=True, to='cars.carimages')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
